/**
 * Generates lib/ai/prompts/templateAssets.ts from the human-editable source of truth:
 *   - system-prompt.txt
 *   - public/contoh-prd.md
 *
 * Run: node scripts/gen-prompts.cjs
 * Why: generation routes must not use fs.readFileSync at runtime (serverless).
 * These constants are bundled into the compiled server output.
 */
const fs = require("fs");
const path = require("path");

const root = path.join(__dirname, "..");
const sys = fs.readFileSync(path.join(root, "system-prompt.txt"), "utf8");
const tpl = fs.readFileSync(path.join(root, "public", "contoh-prd.md"), "utf8");

const out = `/**
 * Bundled prompt assets - DO NOT EDIT BY HAND.
 * Generated by \`node scripts/gen-prompts.cjs\`.
 *
 * These strings ship inside the compiled server bundle so generation routes no
 * longer depend on fs.readFileSync(process.cwd(), ...) at runtime, which is
 * unreliable on serverless runtimes (Vercel) where the filesystem isn't present.
 *
 * Source files (human-editable source of truth):
 *   - system-prompt.txt
 *   - public/contoh-prd.md
 */

export const BASE_SYSTEM_PROMPT = ${JSON.stringify(sys)};

export const PRD_TEMPLATE = ${JSON.stringify(tpl)};

export const PRD_TEMPLATE_FALLBACK =
  "# PRODUCT REQUIREMENTS DOCUMENT (PRD)\\n\\n## 1. Overview\\n\\n## 2. Objectives\\n\\n...";
`;

fs.mkdirSync(path.join(root, "lib", "ai", "prompts"), { recursive: true });
fs.writeFileSync(path.join(root, "lib", "ai", "prompts", "templateAssets.ts"), out);
fs.mkdirSync(path.join(root, "lib", "prompts"), { recursive: true });
fs.writeFileSync(path.join(root, "lib", "prompts", "templateAssets.ts"), out);
console.log("Wrote lib/ai/prompts/templateAssets.ts", out.length, "bytes");